# Generated by Django 3.2 on 2021-04-13 12:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cli', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_cli', models.CharField(max_length=40, verbose_name='nome do cliente')),
                ('fone', models.CharField(max_length=15, verbose_name='telefone')),
                ('rua', models.CharField(max_length=40, verbose_name='nome da rua')),
                ('numero', models.IntegerField(verbose_name='número')),
                ('bairro', models.CharField(max_length=20, verbose_name='bairro')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='complemento')),
                ('cidade', models.CharField(max_length=20, verbose_name='cidade')),
                ('uf', models.CharField(default='PB', max_length=2, verbose_name='unidade federativa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod_prod', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc_prod', models.CharField(max_length=20, verbose_name='descrição do produto')),
                ('unidade', models.CharField(max_length=10, verbose_name='unidade')),
                ('valor_prod', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('cod_vend', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_vend', models.CharField(max_length=40, verbose_name='nome do vendedor')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='salário')),
                ('faixa_comissao', models.CharField(choices=[('A', 'Faixa A'), ('B', 'Faixa B'), ('C', 'Faixa C')], max_length=1, verbose_name='faixa de comissao')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('num_pod', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_ped', models.DateField(verbose_name='data')),
                ('prazo_entrega', models.DateField(blank=True, null=True, verbose_name='data de entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.cliente', verbose_name='cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.vendedor', verbose_name='vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade do produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.produto', verbose_name='produto')),
            ],
            options={
                'unique_together': {('pedido', 'produto')},
            },
        ),
    ]
